title: Patrick Cannon
logo: /assets/img/Patrick_BW_square.png
description: ""
show_downloads: true
google_analytics: true
theme: jekyll-theme-minimal
permalink: pretty
# Eclude CV from navigation
# exclude:
#   - cv.md