title: Patrick Cannon
logo: /assets/img/IMG_9480_small.jpeg
description: ""
show_downloads: true
google_analytics: true
theme: jekyll-theme-minimal
permalink: pretty
kramdown:
  math_engine: null
# Exclude CV from navigation
# exclude:
#   - cv.md